networks:
  pantheon-network:
    driver: bridge
    name: pantheon-network

services:
  # PostgreSQL databaza
  db:
    image: postgres-taskmaster-db:${IMAGE_TAG:-latest} 
    build:
      context: .
      dockerfile: Dockerfile.db
    container_name: taskmaster-db
    networks:
      - pantheon-network
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      # init.sql sa spusti automaticky pri prvom starte
      # funguje len hostovi -> /Users/renemartin/Desktop/pantheon/backend/init.sql
      # cez jenkins agent (cez docker.sock) sa to hlada v /home/jenkins/agent/workspace/pantheon/backend/init.sql -> neexistuje na hostovi
      # - Agent je v kontajneri, working directory: /home/jenkins/agent/workspace/pantheon/backend/                        
      # - ./init.sql → /home/jenkins/agent/workspace/pantheon/backend/init.sql                                             
      # - Docker daemon na hostovi hľadá túto cestu na macOS                                                               
      # - Cesta /home/jenkins/agent/... na macOS neexistuje ❌
      
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

      # persist data medzi restartami
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U taskmaster -d taskmaster_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  # FastAPI aplikacia
  api:
    image: python-taskmaster-api:${IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: taskmaster-api
    networks:
      - pantheon-network
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      # test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')"]
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

volumes:
  postgres_data:
